# Matrizenrechnung mit Python

<!-- Würde man die Spannung von Schraubenschlüsseln einem Mediziner und das Erstellen von Computertomographien (CT) anhand von Strahlen-Messungen einer Ingenieurin vorlegen, so wüsste vermutlich weder der eine noch die andere, was beides miteinander zu tun haben. Die Informatik als Schnittstelle weiß dagegen mehr, denn wenn es aus heutiger Sicht darum geht, dass Informatiksysteme sowohl Spannungen als auch CT's berechnen bzw. erstellen, dann müssen in beiden Fällen $\textit{große, lineare Gleichungssysteme}$ erstellt und gelöst werden. Nun ist es so, dass besagte Gleichungssysteme enormen Aufwand und Mühsal beim Aufschreiben bedeuten, sodass dafür das übersichtliche Schema der sogenannten $\textit{Matrizen}$ entwickelt wurde.<br> Im weiteren Verlauf werden Sie sich mit Theorien der linearen Algebra auseinandersetzen und Matrizen haben sich dafür als unverzichtbar herausgestellt. Daher sollen Sie in diesem Notebook erste $\textit{Konzepte}$ und $\textit{Rechenregeln}$ der Matrizen kennenlernen, um ein Gefühl dafür zu entwickeln, wie man mit ihnen arbeitet und rechnet.
-->

Dieses Notebook soll Sie darin schulen, in dem Umgang mit Matrizen in Python-Code vertrauter zu werden. Sie werden kennenlernen, wie Matrizen in Python initialisiert werden und wie man mit ihnen anschließend rechnet. Dazu werden bekannte mathematische Konzepte wie die Multiplikation von Matrizen in Python-Code umgesetzt. Das darauf aufbauende Notebook "Weitere Operationen von Matrizen" soll entsprechendes Wissen über Python und die Implementierung weiterer Konzepte vertiefen.

<b> Python Grundlagen: </b>  Umgang mit NumPy wünschenswert, Kontrollstrukturen, Schleifen, Variablen <br>
<b> Math. Grundlagen: </b> Vektoren, Matrizen, lineare Gleichungssysteme <br>

<ul>
 <li><a href="#1">Einstieg</a></li>
 <li><a href="#2">Verknüpfungen für Matrizen</a></li>
 <li><a href="#3">Rechenregeln</a></li>
</ul>


Sie werden einige Module zur korrekten Implementierung benötigen. Führen Sie daher zum Start die folgende Code-Zelle aus:

In [4]:
# Import von benötigten Modulen
import numpy as np

## Einstieg <a id="1"></a>

$\textsf{Erinnerung}$: Sei $K$ ein Körper, betrachten Sie z.B. die reellen Zahlen $K = \mathbb{R}$. Für natürliche Zahlen $m,n$ ist dann eine $m \times n- \text{Matrix }A$  eine $\text{rechteckige Anordnung}$ von $\color{cyanorange} \text{Koeffizienten (Einträgen)}$ $a_{ij} \in K$ mit $i =1,\dots, m$ und $j = 1, \dots, n$. Man sagt, die Matrix $A$ habe $m$ $\text{Zeilen}$ und $n$ $\text{Spalten}$, wobei die $a_{ij}$ auch $\text{Einträge}$ der Matrix genannt werden. 

Nehmen Sie ein paar Beispiele zur Hand. Die Matrizen $A, B$ und $C$ seien beschrieben durch $$ A =
\begin{pmatrix*}[r]
3 & 0 & 2  \\
-9 &6 & 0 \\
\end{pmatrix*},\quad
B=\begin{pmatrix}
2 & 2 \\
5 & 1  \\
\end{pmatrix}, \quad
C=\begin{pmatrix}
8  \\
3   \\ 
\end{pmatrix}.$$ 

Folglich handelt es sich bei $A$ um eine $2 \times 3$-Matrix, bei $B$ um eine $ 2 \times 2$ und bei $C$ um eine $2 \times 1$ Matrix. Der Eintrag in der $1$. Zeile und $2$. Spalte der Matrix $A$ lautet dann $$ a_{12} = 0,$$ wohingegen $ b_{12} = 2$ gilt. Weitere einfache, aber nicht weniger wichtige Beispiele sind sowohl die $n \times n-\text{Einheitsmatrix}$  $E_n = 
\begin{pmatrix}
1 &  & 0 \\
 & \ddots & \\
0 &  & 1 
\end{pmatrix}
$, als auch die $n \times n-\text{Nullmatrix}$  $\mathbf{0} = 
\begin{pmatrix}
0 & \cdots & 0 \\
 \vdots & \ddots & \vdots\\
0 & \cdots & 0 
\end{pmatrix}
$.

### Realisierung in Python

In Python werden Matrizen als mehrdimensionale Listen initialisiert. Man kann dafür die in Python integrierten Standarbibliothek für Listen verwenden, wodurch die Initialisierung einer $2 \times 2$-Matrix $ A =
\begin{pmatrix}
1 & 2 \\
3 & 4 \\
\end{pmatrix}$ folgendermaßen aussähe <center><code> A = [[1,2],[3,4]]</code>.</center> Die Matrix wird demnach zeilenweise in Teillisten abgespeichert.

Allerdings bietet das Modul <code>numpy</code> ein größeres Arsenal an Funktionen an, die später auf Matrizen angewendet werden sollen. Eine Initialisierung der gleichen Matrix sähe über <code>numpy</code> dann so aus: <center><code>A = np.array([[1,2],[3,4]])</code>.</center> 

Im weiteren Verlauf werden Sie <code>numpy</code> zum Initialisieren verwenden. Machen Sie sich auch die unterschiedliche Darstellung in der Ausgabe bewusst, indem Sie die Code-Zeilen der folgenden Zelle ausführen:


In [28]:
A = [[1, 2], [3, 4]]
print("Standardbibliothek:\n", A, "\n")

A = np.array([[1, 2], [3, 4]])
print("numpy:\n", A)

Standardbibliothek:
 [[1, 2], [3, 4]] 

numpy:
 [[1 2]
 [3 4]]


Es kann ebenso hilfreich sein, auf die Größenordnung einer Matrix $A$ zurückzugreifen. <code>numpy</code> stellt dafür die Funktion <code>shape</code> zur Verfügung und liefert als Ergebnis selbst ein Array zurück. Das erste Element mit Index $0$ gibt die Zeilenanzahl, das zweite Element mit Index $1$ gibt entsprechend die Spaltenzahl zurück. 

In [29]:
A = np.array([[1, 2, 3], [4, 5, 6]])

print("Die Matrix A =\n", A, "\n")
print("hat", A.shape[0], "Zeilen und", A.shape[1], "Spalten")

Die Matrix A =
 [[1 2 3]
 [4 5 6]] 

hat 2 Zeilen und 3 Spalten



<div style= "color: black;background-color: powderblue ;margin: 10 px auto; padding: 10px; border-radius: 10px">
    <p style="font-size:12pt; text-align:center; color:   black; background-color: lightskyblue ;margin: 10 px auto; padding: 10px; border-radius: 10px" id="1"><b>Aufgabe 1</b>  </p> 

    
Initialisieren Sie folgende Matrizen $A$, $B$ und $C$, indem Sie in der folgenden Zelle die Code-Zeilen entsprechend ergänzen. Lassen Sie ebenfalls die Größenordnung der Matrix $C$ ausgeben:
$$
A=\begin{pmatrix}
6 & 2 & 2 \\
1 & 9 & 5 \\
0 & 8 & 7
\end{pmatrix},\quad
 B=\begin{pmatrix}
2 & 2 & 4 \\
0 & 5 & 0 \\
\end{pmatrix}, \quad
C=\begin{pmatrix}
0 & 3  \\
1 & 5  \\
4 & 7 
\end{pmatrix}
$$

In [ ]:
A = # ???
print("A = \n", A, "\n")

B = # ???
print("B = \n", B, "\n")

C = # ???
print("C = \n", C, "\n\nmit Zeilenzahl", ... , "und Spaltenzahl", ...)  # ???

A = 
 [[6 2 2]
 [1 9 5]
 [0 8 7]] 

B = 
 [[2 2 4]
 [0 5 0]] 

C = 
 [[0 3]
 [1 5]
 [4 7]] 

mit Zeilenzahl 3 und Spaltenzahl 2


## Verknüpfungen für Matrizen <a id="2"></a>
### Addition und skalare Multiplikation

Genau wie es für reelle Zahlen üblich ist, gibt es ebenso für Matrizen Rechenregeln zu beachten. Matrizen $A$ und $B$ können nur mit gleicher Größenordnung komponentenweise addiert und jegliche Matrizen mit Skalaren multipliziert werden:<br> 
 $\begin{align}  (A + B)_{ij} &=a_{ij} + b_{ij} \nonumber,\\[2pt](\lambda  A)_{ij} &=  \lambda a_{ij}\nonumber\end{align}$

Konkret ergibt sich als Beispiel $$\begin{pmatrix} 1 & 2  \\ 0 & 4  \end{pmatrix} + \begin{pmatrix} 6 & 2 \\ 8 & 7 \end{pmatrix} = \begin{pmatrix} 7 & 4 \\ 8 & 11 \end{pmatrix}$$ und $$ 3\begin{pmatrix} 6 & 2 \\ 8 & 7 \end{pmatrix} = \begin{pmatrix} 18 & 6 \\ 24 & 21 \end{pmatrix} .$$



<div style= "color: black;background-color: powderblue ;margin: 10 px auto; padding: 10px; border-radius: 10px">
    <p style="font-size:12pt; text-align:center; color:   black; background-color: lightskyblue ;margin: 10 px auto; padding: 10px; border-radius: 10px" id="1"><b>Aufgabe 2</b>  </p> 

Nehmen Sie wieder die Matrix $ A =\begin{pmatrix}
6 & 2 & 2 \\
1 & 9 & 5 \\
0 & 8 & 7
\end{pmatrix}$ zur Hand und überlegen Sie sich selbst eine Matrix $D$, die die gleiche Größenordnung besitzt und berechnen Sie $A+D$, $A-D$, sowie $ 5 A$ schriftlich. Anschließend initialisieren Sie $D$ und überprüfen Ihr Ergebnis mit Hilfe der Ausgabe.

In [31]:
A = np.array([[6, 2, 2], [1, 9, 5], [0, 8, 7]])
D = # ???
print(" Matrix A =\n", A, "\n")
print(" Matrix D =\n", D, "\n")
print("Dann gilt: A + D =\n", A + D, ",\n")
print("A - D =\n", A - D, "\n")
print("und 5A =\n", 5 * A)

 Matrix A =
 [[6 2 2]
 [1 9 5]
 [0 8 7]] 

 Matrix D =
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

Dann gilt: A + D =
 [[ 7  4  5]
 [ 5 14 11]
 [ 7 16 16]] ,

A - D =
 [[ 5  0 -1]
 [-3  4 -1]
 [-7  0 -2]] 

und 5A =
 [[30 10 10]
 [ 5 45 25]
 [ 0 40 35]]


### Multiplikation

Man kann auch Matrizen miteinander multiplizieren, allerdings ist die Vorgehensweise hier eine andere. Statt, dass alle Einträge einfach miteinander multipliziert werden, folgt man hier dem Gesetz, das sich aus den linearen Gleichungssystem ableiten lässt. Dabei müssen Sie nur beachten, dass zwei Matrizen zueinander kompatibel sind, d.h.:

Sind $A$ eine $m \times n$- und $B$ eine $n \times p$-Matrix, d.h. die Spaltenzahl von $A$ $\textit{muss}$ mit der Zeilenzahl von $B$ übereinstimmen, dann ist das Matrizenprodukt $C = AB$ gegeben durch $$ c_{ik} = \sum_{j=0}^n a_{ij}b_{jk} = a_{i1}b_{1k} + a_{i2}b_{2k} + \ldots + a_{in}b_{nk}$$ für $ i=1,\ldots, m$ und $k = 1,\dots, p$. Beispielsweise ist $$\begin{pmatrix*}[r] 1 & 4 & -1 & 2 \\2 & 1 & -1 & -2 \\2 & 3 & 0 & -3\end{pmatrix*} \cdot \begin{pmatrix*}[r] 1 & 2\\-1 & 1\\2 & -3\\2 & 0\\\end{pmatrix*} = \begin{pmatrix*}[r] -1 & 9\\-5 & 8\\-7 & 7\end{pmatrix*}.$$

Das Potenzieren einer Matrix lässt sich für quadratische Matrizen entsprechend ableiten. Man setzt $A^0 \coloneqq E_n$ und $$ A^n \coloneqq \underbrace{A \cdot \ldots \cdot A}_{n-\textsf{mal}}$$
In Python lässt sich die Matrixmultiplikation dann über zwei Wege realisieren. Nutzen Sie dafür den <code>@</code>-Operator oder die <code>dot()</code>-Funktion des <code>numpy</code>-Moduls. 

$\textsf{Vorsicht}$: Im Fall von quadratischen Matrizen $A,B$, für die $A\cdot B$ existiert, wäre es falsch anzunehmen, dass, wie bei den reellen Zahlen, die Reihenfolge der Matrizenmultiplikation unerheblich ist. Machen Sie sich an einem Beispiel von $2 \times 2$-Matrizen deutlich, dass Matrizen $\textsf{im Allgemeinen nicht kommutieren}$, d.h. es gilt $$ AB \neq BA.$$ 

<div style= "color: black;background-color: powderblue ;margin: 10 px auto; padding: 10px; border-radius: 10px">
    <p style="font-size:12pt; text-align:center; color:   black; background-color: lightskyblue ;margin: 10 px auto; padding: 10px; border-radius: 10px" id="1"><b>Aufgabe 3</b>  </p> 

1. Berechnen Sie das Produkt der Matrizen $A$ und $D$ aus Aufgabe $2$ und überprüfen Sie Ihr Ergebnis über die Befehle <code>A @ D</code> bzw. <code>A.dot(D)</code>. Finden Sie ein geeignetes Beispiel, um zu zeigen, dass das Matrixprodukt nicht kommutativ ist. Initalisieren Sie dazu Ihr Gegenbeispiel in der Code-Zelle und überprüfen die Konsolenausgabe nach Ausführung des Codes.

2. Ergänzen Sie den Code in der mit <b> Teil 2 </b> gekenzeichneten Stelle, um zu prüfen, ob für zwei vorgegebene Matrizen $F$ und $G$ das Produkt $FG$ existiert. Testen Sie Ihren Code anschließend an ausgewählten Beispielen.

In [32]:
# --- Teil 1 ---
A = np.array([[6, 2, 2], [1, 9, 5], [0, 8, 7]])
D = # ???
print("A @ D =\n", A @ D, "\n")
print("A.dot(D) =\n", A.dot(D))
print(A @ D)

# Initialisieren Sie hier Ihre ausgewählten Gegenbeispiele und überprüfen die Behauptung
M = # ???

N = # ???
print("\nMN =\n", M.dot(N), "\n\nwobei NM =\n", N.dot(M))


# --- Teil 2 ---
# hier Code ergänzen
F = # ???
G = # ???

if F.shape[1] == ... :  # ???
    print("\nF und G können miteinander multipliziert werden!\nEs ist FG =\n", ...)  # ???
else:
    print("F und G können nicht miteinander multipliziert werden!")

A @ D =
 [[ 28  38  48]
 [ 72  87 102]
 [ 81  96 111]] 

A.dot(D) =
 [[ 28  38  48]
 [ 72  87 102]
 [ 81  96 111]]
[[ 28  38  48]
 [ 72  87 102]
 [ 81  96 111]]

MN =
 [[0 1]
 [0 0]] 

wobei NM =
 [[0 0]
 [0 0]]
F und G können nicht miteinander multipliziert werden!


## Rechenregeln <a id="3"></a>
Sie kennen ebenfalls das Assoziativ- und Distributivgesetz. Für Matrizen $A$,$B$ und $C$ gilt $ \begin{align} A(B+C) = AB+AC \quad \text{ und }\quad (A+B) C = AC + BC \nonumber\end{align},$ sowie $$ A(BC) = (AB)C.$$


<div style= "color: black;background-color: powderblue ;margin: 10 px auto; padding: 10px; border-radius: 10px">
    <p style="font-size:12pt; text-align:center; color:   black; background-color: lightskyblue ;margin: 10 px auto; padding: 10px; border-radius: 10px" id="1"><b>Aufgabe 4</b>  </p> 
    
Vertiefen Sie in dieser Aufgabe Ihre Kenntnisse zu Rechenoperationen von Matrizen, indem Sie folgende Aufgaben bearbeiten:

1. Finden sie eine $3\times 3$-Matrix $A$, sodass $A^3 = \mathbf{0}$. Überprüfen Sie in der Ausgabe Ihr Ergebnis.

2. Finden Sie zur Matrix $B = \begin{pmatrix*}[r] 1 & 0\\-1 & 1\end{pmatrix*}$ eine geeignete Matrix $C$ mit $BC = \begin{pmatrix*}[r] 1 & 0\\0 & 1\end{pmatrix*}$. Überprüfen Sie ebenfalls ihre Eingabe in der Ausgabe.


In [33]:
# Teilaufgabe 1

A = # ???

result = A @ A @ A
print("A^3 = ", result)

A^3 =  [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [34]:
# Teilaufgabe 2

B = np.array([[1, 0], [-1, 1]])
C = # ???

E = np.array([[1, 0], [0, 1]])

result = B @ C

if np.array_equal(result, E):
    print("Ihre Matrix C ist korrekt: BC =\n", result)
else:
    print("Ihre Matrix C ist nicht korrekt, denn BC =\n", result)

Ihre Matrix C ist korrekt: BC =
 [[1 0]
 [0 1]]


### Lineare Gleichungssysteme

Wie schon anfangs vorgestellt, ist die Matrix insbesondere beim Lösen von linearen Gleichungssystemen (LGS) hilfreich. Nimmt man das LGS 
$$ \begin{align*} x_1 + 2x_2 +3x_3 &= 6 \\ 5x_2 +4x_3 &= 9 \\ 6x_1 + x_2 +x_3 &= 8 \end{align*}$$

so lässt sich dieses in der kompakten $\textsf{Matrix-Vektor-Multiplikation}$ 
$$\begin{pmatrix*}[r] 1 & 2 & 3\\ 0 & 5 & 4\\6 & 1 & 3\\\end{pmatrix*}\cdot \begin{pmatrix*}[r] x_1 \\ x_2 \\ x_3\end{pmatrix*} =  \begin{pmatrix*}[r] 6 \\ 9 \\ 8\end{pmatrix*} $$

oder $\textsf{erweiterten Koeffizientenmatrix}$ darstellen. Solche LGS können Sie mit dem Gauß'schen Eliminationsverfahren per Hand oder mithilfe von <code>numpy</code> durch die Funktion <code>linalg.solve</code> lösen. Zur Erinnerung, ein LGS kann eindeutig oder allgemein lösbar, oder aber unlösbar sein. Ein Beispiel dazu finden Sie in der folgenden Code-Zelle:

In [35]:
A = np.array([[1, 2, 3], [0, 5, 4], [6, 1, 1]])
B = np.array([[-4, 10, 9], [-1, 3, 3], [-2, 4, 3]])

C = np.array([6, 9, 8])  # Achten Sie auf die Schreibweise des Vektors

try:
    X = np.linalg.solve(A, C)
    print("Die Lösung des LGS AX = C lautet:\nX =", X)
except Exception as e:
    print("\nLGS AX = C ist unlösbar -> Exception LinAlgError:", e)

try:
    X = np.linalg.solve(B, C)
    print("Die Lösung des LGS BX = C lautet:\nX =", X)
except Exception as e:
    print("\nLGS BX = C ist unlösbar -> Exception LinAlgError:", e)

Die Lösung des LGS AX = C lautet:
X = [1. 1. 1.]

LGS BX = C ist unlösbar -> Exception LinAlgError: Singular matrix


<div style= "color: black;background-color: powderblue ;margin: 10 px auto; padding: 10px; border-radius: 10px">
    <p style="font-size:12pt; text-align:center; color:   black; background-color: lightskyblue ;margin: 10 px auto; padding: 10px; border-radius: 10px" id="1"><b>Aufgabe 5</b>  </p> 
    
1. Berechnen sie die Lösungen der folgenden LGS: 
$$ \text{a)} \quad \begin{pmatrix*}[r] 1 & 2 & 3\\ 0 & 5 & 4\\6 & 1 & 1\\\end{pmatrix*}\cdot \begin{pmatrix*}[r] x_1 \\ x_2 \\ x_3\end{pmatrix*} =  \begin{pmatrix*}[r] 6 \\ 9 \\ 8\end{pmatrix*} \quad\quad\text{b)} \quad \begin{pmatrix*}[r] 1 & 0 & 1\\ 1 & 0 & 1\\2 & 1 & 0\\\end{pmatrix*}\cdot \begin{pmatrix*}[r] x_1 \\ x_2 \\ x_3\end{pmatrix*} =  \begin{pmatrix*}[r]10 \\ 12 \\ 9\end{pmatrix*} $$

2. Finden Sie ein $t \in \mathbb{R}$, sodass das folgende LGS eindeutig lösbar wird $$\begin{align*} x_1 + tx_2 &= 1 \\ 2tx_1 +3x_2 &= 0 \end{align*}$$

Überprüfen Sie anschließend Ihre Lösungen.

In [36]:
# Teilaufgabe 1 a)
A = np.array([[1, 2, 3], [0, 5, 4], [6, 1, 1]])
X = # hier möglichen Lösungsvektor eintragen
B = np.array([6, 9, 8])


possible = (
    ...  # legen sie zunächst fest (True/False), ob das LGS lösbar ist oder nicht
)
solvable = True
antwort = "lösbar" if possible == True else "unlösbar"

# den nachfolgende Code-Abschnitt müssen Sie nicht nachvollziehen
try:
    Y = np.linalg.solve(A, B)
    print("Das LGS AX = B ist lösbar.")
except Exception as e:
    print("\nLGS AX = B ist unlösbar -> Exception LinAlgError:", e)
    solvable = False

print("Ihre Antwort zur Lösbarkeit:", antwort)

if solvable and possible:
    if np.array_equal(A @ X, B):
        print("\nIhr Lösungsvektor X =", X, "ist korrekt.")
    else:
        print("\nIhr Lösungsvektor X =", X, "ist nicht korrekt.")

Das LGS AX = B ist lösbar.
Ihre Antwort zur Lösbarkeit: lösbar

Ihr Lösungsvektor X = [0 0 0] ist nicht korrekt.


In [37]:
# Teilaufgabe 1 b)

A = np.array([[1, 0, 1], [1, 0, 1], [2, 1, 0]])
X = # hier möglichen Lösungsvektor eintragen
B = np.array([10, 12, 9])


possible = (
    ...  # legen sie zunächst fest (True/False), ob das LGS lösbar ist oder nicht
)
solvable = True
antwort = "lösbar" if possible == True else "unlösbar"

# den nachfolgende Code-Abschnitt müssen Sie nicht nachvollziehen
try:
    Y = np.linalg.solve(A, B)
    print("Das LGS AX = B ist lösbar.")

except Exception as e:
    print("\nLGS AX = B ist unlösbar -> Exception LinAlgError:", e)
    solvable = False

print("Ihre Antwort zur Lösbarkeit:", antwort)

if solvable and possible:
    if np.array_equal(A @ X, B):
        print("\nIhr Lösungsvektor X =", X, "ist korrekt.")
    else:
        print("\nIhr Lösungsvektor X =", X, "ist nicht korrekt.")


LGS AX = B ist unlösbar -> Exception LinAlgError: Singular matrix
Ihre Antwort zur Lösbarkeit: unlösbar


In [5]:
# Teilaufgabe 2
t = 7  # Tragen Sie hier Ihren Wert für t ein und führen Sie zunächst diese Zelle aus.

In [11]:
# Führen Sie anschließend diese Zelle aus



if t != np.sqrt(3 / 2):


    print(
        "Ihre Lösung für t =",
        t,

        "ist korrekt. Das LGS\n\n x_1 +",
        t,

        "x_2 = 1\n",
        2 * t,
        "x_1 + 3 x_2 = 0\n\nist eindeutig lösbar.",
    )


else:


    print("Ihre Lösung für t =", t, "ist nicht korrekt.")

Ihre Lösung für t = 7 ist korrekt. Das LGS

 x_1 + 7 x_2 = 1
 14 x_1 + 3 x_2 = 0

ist eindeutig lösbar.
